# Homarr's Dex client (dex/application.yaml)
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: auth-oidc-secret
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials # kube/infisical.sops.yaml
        secretNamespace: infisical
      secretsScope:
        projectSlug: lab
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: auth-oidc-secret
      secretNamespace: homarr
      creationPolicy: Owner
      secretType: Opaque
      template:
        data:
          oidc-client-id: 'homarr'
          oidc-client-secret: '{{ .HOMARR_CLIENT_SECRET.Value }}'
