apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager # also what the chart sees as its release namespace
helmCharts:
  - name: cert-manager-webhook-duckdns
    repo: oci://ghcr.io/cobexer/charts
    version: 2.0.0
    releaseName: cert-manager-webhook-duckdns
    valuesFile: values.yaml
    includeCRDs: true
