apiVersion: v1
kind: Namespace
metadata:
    name: infisical
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWFtTTUzdkFEaUhOSUdw
            bnk5cHduMTE0bDdNbVJ1aTY2Vlc3ak0vK0dvCkR6Z0lNOTNVV0JNSmFHYzRqa0Vs
            aWljUU9ENG5JRE1LKzNOMDZlWVA2T1EKLS0tIEZFejc1aldhMlY5c2xjbFhkc2V5
            YnVya21jK29wM05rOFRqU3pYejB6VTAKvOf6z4hcTR2A84EJfOWtLrtSShFkPZFU
            qp8aVs+D7RJ5e2jHfbs8Rj0LMenrGbfS504n2AiDh3HuY3HyqZtBig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkq8prdy8ze4aq9cacm7kn2ft3paevtzdlu36629c6tauhp4upas8rt7tf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:45:48Z"
    mac: ENC[AES256_GCM,data:ZSMEHwN5KMhKzWsjoqfwkmh3eUYTEjIMHbplsa0cNPGLjSGTcRRdyJA/Qxlik5isB83VgU3Q11DbYy8nGnTpRYe+H8bLcKaNq5GRokUVLYEMODqsUXfCJIW4wEyVUyH6/Gi53nDf1xBL5xuvwOTH9z1ot223Aybl1wCbQtEFBBU=,iv:h8JUhmPkqAwITZB/fdZs+X5XmN0HtJcXH+2sL7srtYE=,tag:4WqpD6hv8WGk4fu8RTDr5w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: universal-auth-credentials
    namespace: infisical
stringData:
    clientId: ENC[AES256_GCM,data:YwEPi5t1Qt4TF2Huyk8g+//xSBiWsMeUmjM/AF/mgKIu+LS4,iv:xpprIPAhrvX1uglNu0r42pxwfUCthmRpTLslvXpQ6Hg=,tag:Yb1i6JlXJB76FlwqGa0IIQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:RJEDwBceQzVCPRYtVUiUH3cfNppb3jcC9IkTnk9lhK/6hE3Dc5zj8XVSF/oxInPpkJhuOu5MFKOS8s5oTgacsg==,iv:szGA+ncrQ9THiwxIZ7XCpHTAOLh6WX/qrlJSOCAP5PA=,tag:dAKmm7rcrUZVPUZpiW5pAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWFtTTUzdkFEaUhOSUdw
            bnk5cHduMTE0bDdNbVJ1aTY2Vlc3ak0vK0dvCkR6Z0lNOTNVV0JNSmFHYzRqa0Vs
            aWljUU9ENG5JRE1LKzNOMDZlWVA2T1EKLS0tIEZFejc1aldhMlY5c2xjbFhkc2V5
            YnVya21jK29wM05rOFRqU3pYejB6VTAKvOf6z4hcTR2A84EJfOWtLrtSShFkPZFU
            qp8aVs+D7RJ5e2jHfbs8Rj0LMenrGbfS504n2AiDh3HuY3HyqZtBig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkq8prdy8ze4aq9cacm7kn2ft3paevtzdlu36629c6tauhp4upas8rt7tf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:45:48Z"
    mac: ENC[AES256_GCM,data:ZSMEHwN5KMhKzWsjoqfwkmh3eUYTEjIMHbplsa0cNPGLjSGTcRRdyJA/Qxlik5isB83VgU3Q11DbYy8nGnTpRYe+H8bLcKaNq5GRokUVLYEMODqsUXfCJIW4wEyVUyH6/Gi53nDf1xBL5xuvwOTH9z1ot223Aybl1wCbQtEFBBU=,iv:h8JUhmPkqAwITZB/fdZs+X5XmN0HtJcXH+2sL7srtYE=,tag:4WqpD6hv8WGk4fu8RTDr5w==,type:str]
    version: 3.13.3
