# DuckDNS API token, for the wildcard certificate's DNS-01 challenges (cert-manager-webhook-duckdns)
apiVersion: v1
kind: Secret
metadata:
    name: duckdns
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:JN92NB7HyjGUDXITqxG8Ss2Q5QBHWlhmk5SN3RFTlStFcWWM,iv:wxNoEBfJGdXFDETVxCN/bee1xH9abEal/XR5I9lAIn8=,tag:JOzKNzeWuMJHD12Qgbiq6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWFtTTUzdkFEaUhOSUdw
            bnk5cHduMTE0bDdNbVJ1aTY2Vlc3ak0vK0dvCkR6Z0lNOTNVV0JNSmFHYzRqa0Vs
            aWljUU9ENG5JRE1LKzNOMDZlWVA2T1EKLS0tIEZFejc1aldhMlY5c2xjbFhkc2V5
            YnVya21jK29wM05rOFRqU3pYejB6VTAKvOf6z4hcTR2A84EJfOWtLrtSShFkPZFU
            qp8aVs+D7RJ5e2jHfbs8Rj0LMenrGbfS504n2AiDh3HuY3HyqZtBig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkq8prdy8ze4aq9cacm7kn2ft3paevtzdlu36629c6tauhp4upas8rt7tf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:19:18Z"
    mac: ENC[AES256_GCM,data:WUOmYlH/CdphwjlRLXvKSqP2F2EQ3Aw1DZf6TKr0sJypET6nSuITu1kMpogi3f5qE36KNIiSCH/ikUzVgDibI0kZk71UeBCLwbMSybmdDdfPwIJAyv6j+FltM9oR8MwDOwvWh/6wflv1RKF6UUfTZb3gVKSh2VK2anjJ5EXSzXw=,iv:rOtl7LB8655x6Ad8poa3MT8YfXS6wn/V9GuI6us8Ytg=,tag:DIs1PZ8F0w1bGEdOMqX8pg==,type:str]
    version: 3.13.3
---
# Homarr's database encryption key: 64 hex chars, e.g. `openssl rand -hex 32`
apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
stringData:
    db-encryption-key: ENC[AES256_GCM,data:eNmRAq5i8CiTaNvBFE614kH1nznNpDWA0vYAg8YSFcbFdrAVDeQcYZ3s/ONMNDjDeZBSeBDgdD0ySK2pQnBQYw==,iv:+OLdIepekwt4ScIkgxuY0FBNDYGQCGN467wmXYeTO7w=,tag:Ezcs1VV8esvsT3rnr8VvOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWFtTTUzdkFEaUhOSUdw
            bnk5cHduMTE0bDdNbVJ1aTY2Vlc3ak0vK0dvCkR6Z0lNOTNVV0JNSmFHYzRqa0Vs
            aWljUU9ENG5JRE1LKzNOMDZlWVA2T1EKLS0tIEZFejc1aldhMlY5c2xjbFhkc2V5
            YnVya21jK29wM05rOFRqU3pYejB6VTAKvOf6z4hcTR2A84EJfOWtLrtSShFkPZFU
            qp8aVs+D7RJ5e2jHfbs8Rj0LMenrGbfS504n2AiDh3HuY3HyqZtBig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkq8prdy8ze4aq9cacm7kn2ft3paevtzdlu36629c6tauhp4upas8rt7tf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:19:18Z"
    mac: ENC[AES256_GCM,data:WUOmYlH/CdphwjlRLXvKSqP2F2EQ3Aw1DZf6TKr0sJypET6nSuITu1kMpogi3f5qE36KNIiSCH/ikUzVgDibI0kZk71UeBCLwbMSybmdDdfPwIJAyv6j+FltM9oR8MwDOwvWh/6wflv1RKF6UUfTZb3gVKSh2VK2anjJ5EXSzXw=,iv:rOtl7LB8655x6Ad8poa3MT8YfXS6wn/V9GuI6us8Ytg=,tag:DIs1PZ8F0w1bGEdOMqX8pg==,type:str]
    version: 3.13.3
