#!/usr/bin/env bash
#MISE description="Render every app's charts with its values.yaml, and validate them and its manifests/ against the schemas"
set -euo pipefail

cd "$MISE_PROJECT_ROOT/kube/apps"

find . -type f -wholename '*.yaml' -and -not -wholename '*/values.yaml' -print0 | xargs -0 kubeconform \
  -strict \
  -summary \
  -verbose \
  -cache /tmp \
  -schema-location default \
  -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
