apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
configMapGenerator:
  - name: homepage-config
    files:
      - configs/settings.yaml
      - configs/widgets.yaml
      - configs/services.yaml
      - configs/bookmarks.yaml
resources:
  - manifests/deployment.yaml
  - manifests/oidc.sops.yaml
  - manifests/route.yaml
  - manifests/securitypolicy.yaml
  - manifests/service.yaml
