# apiVersion and kind only for Renovate's argocd manager, which reads charts from Application files
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-duckdns
spec:
  project: default
  destination:
    namespace: cert-manager
  sources:
    - repoURL: ghcr.io/cobexer/charts
      chart: cert-manager-webhook-duckdns
      targetRevision: 2.0.0
