namespace: media
repo: https://jellyfin.github.io/jellyfin-helm
chart: jellyfin
version: 3.2.0
values:
  persistence:
    media:
      existingClaim: media # pvc.yaml
    config:
      storageClass: openebs-hostpath
