apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  annotations:
    k8up.io/backup: "false" # the media itself: too big for the backup quota
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 25Gi
