# the root app: syncs this directory (the ApplicationSet and itself); created by argocd-bootstrap
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dawidd6/lab
    targetRevision: master
    path: kube/apps/root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
