apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb # also what the chart sees as its release namespace
helmCharts:
  - name: metallb
    repo: oci://quay.io/metallb/chart
    version: 0.16.1
    releaseName: metallb
    valuesFile: values.yaml
    includeCRDs: true
