- name: Provision OS
  hosts: servers
  gather_facts: false
  tasks:
    - name: Set nopasswd for sudo group
      become: true
      community.general.sudoers:
        name: sudo-nopasswd
        group: sudo
        commands: ALL
        nopassword: true
