- name: Provision OS
  hosts: servers
  tasks:
    - name: Set nopasswd for sudo group
      become: true
      community.general.sudoers:
        name: sudo-nopasswd
        group: sudo
        commands: ALL
        nopassword: true

    - name: Install Tailscale
      become: true
      ansible.builtin.shell:
        cmd: set -o pipefail && curl -fsSL https://tailscale.com/install.sh | sh
        creates: /usr/bin/tailscale

    - name: Bring up Tailscale
      become: true
      ansible.builtin.command: tailscale up --reset --advertise-routes={{ ansible_facts.default_ipv4.address }}/32 --ssh
      async: 600
      poll: 0
      changed_when: false

    - name: Wait for Tailscale to come up or ask for a login
      become: true
      ansible.builtin.command: tailscale status --json
      register: tailscale
      until: (tailscale.stdout | from_json).BackendState == 'Running' or (tailscale.stdout | from_json).AuthURL != ''
      retries: 30
      delay: 1
      changed_when: false

    - name: Log in to the tailnet
      when: (tailscale.stdout | from_json).BackendState != 'Running'
      ansible.builtin.pause:
        prompt: "Open {{ (tailscale.stdout | from_json).AuthURL }} to add {{ inventory_hostname }} to the tailnet, then press Enter"
