apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs # also what the chart sees as its release namespace
helmCharts:
  - name: openebs
    repo: oci://ghcr.io/openebs/charts
    version: 4.6.1
    releaseName: openebs
    valuesFile: values.yaml
    includeCRDs: true
