apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/openebs/charts
      chart: openebs
      targetRevision: 4.6.1
      helm:
        releaseName: openebs
        valuesObject:
          global:
            kubeletDir: /var/lib/k0s/kubelet/
          engines:
            local:
              lvm:
                enabled: false
              hostpath:
                enabled: true
              zfs:
                enabled: false
              rawfile:
                enabled: false
            replicated:
              mayastor:
                enabled: false
          loki:
            enabled: false
          alloy:
            enabled: false
    - repoURL: https://github.com/dawidd6/lab # this directory's other manifests
      targetRevision: master
      path: kube/apps/openebs
      directory:
        exclude: application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true # CRs whose CRDs another app or this app's chart installs
