# read by root/applicationset.yaml, which adds this directory's values.yaml and manifests and what every app shares
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    namespace: envoy-gateway
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: 1.9.2
