apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - manifests/deployment.yaml
  - manifests/oidc.sops.yaml
  - manifests/pvc.yaml
  - manifests/route.yaml
  - manifests/securitypolicy.yaml
  - manifests/service.yaml
