apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.duckdns.org # must match the webhook chart's groupName
            solverName: duckdns
            config:
              apiTokenSecretRef:
                name: duckdns
                key: token
